spring:
  application:
    name: spring.kafka.stream
  kafka:
     bootstrap-servers: localhost:9092
     consumer:
        group-id: group_id
        auto-offset-reset: earliest
     streams:
       default-key-serde-class: org.apache.kafka.common.serialization.Serdes$StringSerde
       default-value-serde-class: org.springframework.kafka.support.serializer.JsonDeserializer   
       application-id: spring.kafka.stream
     producer:
       acks: all
       